# Fantasy Landscape
# preload = ~/.config/backgrounds/Fantasy-Landscape3.png
# wallpaper = , ~/.config/backgrounds/Fantasy-Landscape3.png

# Fantasy Landscape 2
# preload = ~/.config/backgrounds/Fantasy-Landscape2.png
# wallpaper = , ~/.config/backgrounds/Fantasy-Landscape2.png

# Fantasy Landscape 2
# preload = ~/.config/backgrounds/Fantasy-Lake2.png
# wallpaper = , ~/.config/backgrounds/Fantasy-Lake2.png

# Cody
preload = ~/.config/backgrounds/Cody.png
wallpaper = , ~/.config/backgrounds/Cody.png

